### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SyVBg0/protobuf

### ISSUE THREAD

**Issue by ZeroTheSavior** [UltrosBot/Ultros#78]
obsidian@obsidian-Ubuntu:~/Downloads$ cd Ultros-1.1.0/
obsidian@obsidian-Ubuntu:~/Downloads/Ultros-1.1.0$ chmod a+x startultros.
chmod: cannot access ‘startultros.’: No such file or directory
obsidian@obsidian-Ubuntu:~/Downloads/Ultros-1.1.0$ chmod a+x startultros.sh
obsidian@obsidian-Ubuntu:~/Downloads/Ultros-1.1.0$ ./startultros.sh 
** Creating virtualenv.. **
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /usr/lib/python2.7/dist-packages
New python executable in Ultros/bin/python
Installing setuptools, pip...done.
** Activating virtualenv.. **
** Installing dependencies.. **
Collecting six>=1.6.1 (from -r requirements.txt (line 1))
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting twisted (from -r requirements.txt (line 2))
  Using cached Twisted-15.3.0.tar.bz2
Requirement already satisfied (use --upgrade to upgrade): zope.interface in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Collecting kitchen (from -r requirements.txt (line 4))
  Using cached kitchen-1.2.1.tar.gz
Collecting yapsy==1.10.2-pythons2n3 (from -r requirements.txt (line 5))
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Yapsy-1.10.2-pythons2n3.tar.gz (146kB)
    100% |████████████████████████████████| 147kB 1.5MB/s 
Collecting pyyaml (from -r requirements.txt (line 6))
  Using cached PyYAML-3.11.tar.gz
Collecting protobuf (from -r requirements.txt (line 7))
  Using cached protobuf-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-build-SyVBg0/protobuf/.eggs/google_apputils-0.4.2-py2.7.egg
    Searching for python-gflags>=1.4
    Reading https://pypi.python.org/simple/python-gflags/
    Reading http://code.google.com/p/python-gflags
    Best match: python-gflags 2.0
    Downloading https://pypi.python.org/packages/source/p/python-gflags/python-gflags-2.0.tar.gz#md5=23c9a793959a54971b1f094b0c6d03b1
    Processing python-gflags-2.0.tar.gz
    Writing /tmp/easy_install-bSRgDH/python-gflags-2.0/setup.cfg
    Running python-gflags-2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bSRgDH/python-gflags-2.0/egg-dist-tmp-Z_POVo
    zip_safe flag not set; analyzing archive contents...
    Moving python_gflags-2.0-py2.7.egg to /tmp/pip-build-SyVBg0/protobuf/.eggs
    
    Installed /tmp/pip-build-SyVBg0/protobuf/.eggs/python_gflags-2.0-py2.7.egg
    Searching for python-dateutil>=1.4
    Reading https://pypi.python.org/simple/python-dateutil/
    Reading http://labix.org/python-dateutil
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-SyVBg0/protobuf/setup.py", line 200, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 310, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 830, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1075, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1087, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 377, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 617, in easy_install
        not self.always_copy, self.local_index
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 590, in fetch_distribution
        self.find_packages(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 427, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name+'/')
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 761, in scan_url
        self.process_url(url, True)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 325, in process_url
        page = self.process_index(url, page)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 404, in process_index
        self.scan_url(new_url)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 761, in scan_url
        self.process_url(url, True)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 312, in process_url
        page = f.read()
      File "/usr/lib/python2.7/socket.py", line 351, in read
        data = self._sock.recv(rbufsize)
      File "/usr/lib/python2.7/httplib.py", line 549, in read
        return self._read_chunked(amt)
      File "/usr/lib/python2.7/httplib.py", line 618, in _read_chunked
        value.append(self._safe_read(chunk_left))
      File "/usr/lib/python2.7/httplib.py", line 664, in _safe_read
        chunk = self.fp.read(min(amt, MAXAMOUNT))
      File "/usr/lib/python2.7/socket.py", line 380, in read
        data = self._sock.recv(left)
    socket.timeout: timed out
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SyVBg0/protobuf
>> Presuming everything installed okay, you should now be ready to run Ultros!
** Renstalling packages.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
^CTraceback (most recent call last):
  File "packages.py", line 47, in <module>
    import pip
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/__init__.py", line 77, in <module>
    logging.getLogger(__name__).addHandler(NullHandler())
  File "/usr/lib/python2.7/logging/__init__.py", line 1559, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/lib/python2.7/logging/__init__.py", line 1035, in getLogger
    self._fixupChildren(ph, rv)
  File "/usr/lib/python2.7/logging/__init__.py", line 1089, in _fixupChildren
    if c.parent.name[:namelen] != name:
KeyboardInterrupt

obsidian@obsidian-Ubuntu:~/Downloads/Ultros-1.1.0$ sudo ./startultros.sh 
[sudo] password for obsidian: 
** Activating virtualenv.. **
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating.. **
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from kitchen.text.converters import getwriter
ImportError: No module named kitchen.text.converters
** Updating plugins.. **
>> You need to run the setup steps first!
** Starting Ultros.. **
^CTraceback (most recent call last):
  File "run.py", line 27, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 90, in <module>
    import textwrap as _textwrap
  File "/usr/lib/python2.7/textwrap.py", line 40, in <module>
    class TextWrapper:
  File "/usr/lib/python2.7/textwrap.py", line 104, in TextWrapper
    wordsep_simple_re = re.compile(r'(\s+)')
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 498, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.7/sre_parse.py", line 678, in parse
    source = Tokenizer(str)
  File "/usr/lib/python2.7/sre_parse.py", line 178, in __init__
    def __init__(self, string):
KeyboardInterrupt
obsidian@obsidian-Ubuntu:~/Downloads/Ultros-1.1.0$

**Comment by gdude2002** [comment]
Hey there, thanks for your ticket. A couple things to note here:

* The problem above appears to be that your connection timed out while downloading Protobuf. Since you're on Linux, just `pip install - r requirements.txt` and it should install. If you're going to use a virtualenv, be sure to enter it before running that. 
* That start script is quite old, and the docs are being rewritten - instead of the looping script, please try the daemonizing scripts in `bin/`

**Comment by gdude2002** [comment]
I'm going to close this ticket for now; feel free to comment again or open a new one if you have any more issues.
